### PR TITLE
fix: typescript TS2371 error

### PR DESCRIPTION
**Pull request by skinnyworm**
Encount compilation error TS2371 when build with typescript > 5.2.

```
TS2371: A parameter initializer is only allowed in a function or constructor implementation.
```

### CODE REVIEW

**Comment by yoshoku** [comment]
Oh, thank you. I forgot that function type definitions cannot have default parameters.

**Review by yoshoku — APPROVED** [review]
